#pragma once

enum eCrimeType : int32_t
{
  CRIME_NONE = 0x0,
  CRIME_POSSESSION_GUN = 0x1,
  CRIME_HIT_PED = 0x2,
  CRIME_HIT_COP = 0x3,
  CRIME_SHOOT_PED = 0x4,
  CRIME_SHOOT_COP = 0x5,
  CRIME_STEAL_CAR = 0x6,
  CRIME_RUN_REDLIGHT = 0x7,
  CRIME_RECKLESS_DRIVING = 0x8,
  CRIME_SPEEDING = 0x9,
  CRIME_RUNOVER_PED = 0xA,
  CRIME_RUNOVER_COP = 0xB,
  CRIME_DESTROY_HELI = 0xC,
  CRIME_PED_SET_ON_FIRE = 0xD,
  CRIME_COP_SET_ON_FIRE = 0xE,
  CRIME_CAR_SET_ON_FIRE = 0xF,
  CRIME_DESTROY_PLANE = 0x10,
  CRIME_CAUSE_EXPLOSION = 0x11,
  CRIME_STAB_PED = 0x12,
  CRIME_STAB_COP = 0x13,
  CRIME_DESTROY_VEHICLE = 0x14,
  CRIME_DAMAGE_TO_PROPERTY = 0x15,
  CRIME_TARGET_COP = 0x16,
  MAX_CRIMES = 0x17,
};