#pragma once

enum eVisibleArea : int32_t
{
  AREA_MAIN_MAP = 0x0,
  AREA_HOTEL = 0x1,
  AREA_MANSION = 0x2,
  AREA_BANK = 0x3,
  AREA_MALL = 0x4,
  AREA_STRIP_CLUB = 0x5,
  AREA_LAWYERS = 0x6,
  AREA_COFFEE_SHOP = 0x7,
  AREA_CONCERT_HALL = 0x8,
  AREA_STUDIO = 0x9,
  AREA_RIFLE_RANGE = 0xA,
  AREA_BIKER_BAR = 0xB,
  AREA_POLICE_STATION = 0xC,
  AREA_EVERYWHERE = 0xD,
  AREA_DIRT = 0xE,
  AREA_BLOOD = 0xF,
  AREA_OVALRING = 0x10,
  AREA_MALIBU_CLUB = 0x11,
  AREA_PRINT_WORKS = 0x12,
  MAX_VISIBLE_AREAS = 0x13,
};