#pragma once

enum eWeaponState : int32_t
{
  WEAPONSTATE_READY = 0x0,
  WEAPONSTATE_FIRING = 0x1,
  WEAPONSTATE_RELOADING = 0x2,
  WEAPONSTATE_OUT_OF_AMMO = 0x3,
  WEAPONSTATE_MELEE_MADECONTACT = 0x4,
};
