#pragma once

enum eWeaponSlot : int32_t
{
  WEAPONSLOT_TYPE_UNARMED = 0x0,
  WEAPONSLOT_TYPE_MELEE = 0x1,
  WEAPONSLOT_TYPE_HANDGUN = 0x2,
  WEAPONSLOT_TYPE_SHOTGUN = 0x3,
  WEAPONSLOT_TYPE_SMG = 0x4,
  WEAPONSLOT_TYPE_RIFLE = 0x5,
  WEAPONSLOT_TYPE_SNIPER = 0x6,
  WEAPONSLOT_TYPE_HEAVY = 0x7,
  WEAPONSLOT_TYPE_THROWN = 0x8,
  WEAPONSLOT_TYPE_SPECIAL = 0x9,
  WEAPONSLOT_TYPE_GIFT = 0xA,
  WEAPONSLOT_TYPE_PARACHUTE = 0xB,
  WEAPONSLOP_TYPE_DETONATOR = 0xC,
};

